spring.application.name=antx
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortner
spring.datasource.username=XXXX
spring.datasource.password=XXXXXXXXXXXX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=2006
